// <auto-generated />
using CurrencyConverter.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CurrencyConverter.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210324221217_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CurrencyConverter.Model.Currency", b =>
                {
                    b.Property<int>("timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("base")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("timestamp");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("CurrencyConverter.Model.Rates", b =>
                {
                    b.Property<int>("timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AED")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AFN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ALL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AMD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ANG")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AOA")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ARS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AUD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AWG")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AZN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BAM")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BBD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BDT")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BGN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BHD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BIF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BMD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BND")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BOB")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BRL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BSD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BTC")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BTN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BWP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BYN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BYR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("BZD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CAD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CDF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CHF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CLF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CLP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CNY")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("COP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CRC")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CUC")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CUP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CVE")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CZK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("DJF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("DKK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("DOP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("DZD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("EGP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ERN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ETB")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("EUR")
                        .HasColumnType("int");

                    b.Property<decimal>("FJD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("FKP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("GBP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("GEL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("GGP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("GHS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("GIP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("GMD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("GNF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("GTQ")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("GYD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("HKD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("HNL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("HRK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("HTG")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("HUF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IDR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ILS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IMP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("INR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IQD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IRR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ISK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("JEP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("JMD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("JOD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("JPY")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("KES")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("KGS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("KHR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("KMF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("KPW")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("KRW")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("KWD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("KYD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("KZT")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LAK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LBP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LKR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LRD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LSL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LTL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LVL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LYD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MAD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MDL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MGA")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MKD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MMK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MNT")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MOP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MRO")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MUR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MVR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MWK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MXN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MYR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MZN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("NAD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("NGN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("NIO")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("NOK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("NPR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("NZD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("OMR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PAB")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PEN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PGK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PHP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PKR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PLN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PYG")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("QAR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("RON")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("RSD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("RUB")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("RWF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SAR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SBD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SCR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SDG")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SEK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SGD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SHP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SLL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SOS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SRD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("STD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SVC")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SYP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SZL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("THB")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TJS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TMT")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TND")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TOP")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TRY")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TTD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TWD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TZS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("UAH")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("UGX")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("USD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("UYU")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("UZS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("VEF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("VND")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("VUV")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("WST")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("XAF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("XAG")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("XAU")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("XCD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("XDR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("XOF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("XPF")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("YER")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ZAR")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ZMK")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ZMW")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ZWL")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("timestamp");

                    b.ToTable("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
