using CurrencyConverter.Model;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Http;
using System.Text;

namespace CurrencyConverter.Schedule
{
    public class CurrencyRateSaveDB
    {
        public static HttpClient webClient = new HttpClient();
        public void Save()
        {            
            string apiUrlLatest = ConfigurationManager.AppSettings.Get("apiUrl") + "latest?" + ConfigurationManager.AppSettings.Get("access_key");
            var webResponse = webClient.GetAsync(apiUrlLatest).Result;
            var data = webResponse.Content.ReadAsAsync<Currency>().Result;

            using (var context = new ApplicationDBContext())
            {
                var currency = new Currency()
                {
                    //timestamp = data.timestamp,
                    timestamp = Convert.ToInt32(DateTimeOffset.Now.ToUnixTimeSeconds()),
                    @base = data.@base,
                    date = data.date                    
                };
                var rates = new Rates()
                {
                    //timestamp = data.timestamp,
                    timestamp = Convert.ToInt32(DateTimeOffset.Now.ToUnixTimeSeconds()),
                    AED = data.Rates.AED,
                    AFN = data.Rates.AFN,
                    ALL = data.Rates.ALL,
                    AMD = data.Rates.AMD,
                    ANG = data.Rates.ANG,
                    AOA = data.Rates.AOA,
                    ARS = data.Rates.ARS,
                    AUD = data.Rates.AUD,
                    AWG = data.Rates.AWG,
                    AZN = data.Rates.AZN,
                    BAM = data.Rates.BAM,
                    BBD = data.Rates.BBD,
                    BDT = data.Rates.BDT,
                    BGN = data.Rates.BGN,
                    BHD = data.Rates.BHD,
                    BIF = data.Rates.BIF,
                    BMD = data.Rates.BMD,
                    BND = data.Rates.BND,
                    BOB = data.Rates.BOB,
                    BRL = data.Rates.BRL,
                    BSD = data.Rates.BSD,
                    BTC = data.Rates.BTC,
                    BTN = data.Rates.BTC,
                    BWP = data.Rates.BWP,
                    BYN = data.Rates.BYN,
                    BYR = data.Rates.BYR,
                    BZD = data.Rates.BZD,
                    CAD = data.Rates.CAD,
                    CDF = data.Rates.CDF,
                    CHF = data.Rates.CHF,
                    CLF = data.Rates.CLF,
                    CLP = data.Rates.CLP,
                    CNY = data.Rates.CNY,
                    COP = data.Rates.COP,
                    CRC = data.Rates.CRC,
                    CUC = data.Rates.CUC,
                    CUP = data.Rates.CUP,
                    CVE = data.Rates.CVE,
                    CZK = data.Rates.CZK,
                    DJF = data.Rates.DJF,
                    DKK = data.Rates.DKK,
                    DOP = data.Rates.DOP,
                    DZD = data.Rates.DZD,
                    EGP = data.Rates.EGP,
                    ERN = data.Rates.ERN,
                    ETB = data.Rates.ETB,
                    EUR = data.Rates.EUR,
                    FJD = data.Rates.FJD,
                    FKP = data.Rates.FKP,
                    GBP = data.Rates.GBP,
                    GEL = data.Rates.GEL,
                    GGP = data.Rates.GGP,
                    GHS = data.Rates.GHS,
                    GIP = data.Rates.GIP,
                    GMD = data.Rates.GMD,
                    GNF = data.Rates.GNF,
                    GTQ = data.Rates.GTQ,
                    GYD = data.Rates.GYD,
                    HKD = data.Rates.HKD,
                    HNL = data.Rates.HNL,
                    HRK = data.Rates.HRK,
                    HTG = data.Rates.HTG,
                    HUF = data.Rates.HUF,
                    IDR = data.Rates.IDR,
                    ILS = data.Rates.ILS,
                    IMP = data.Rates.IMP,
                    INR = data.Rates.INR,
                    IQD = data.Rates.IQD,
                    IRR = data.Rates.IRR,
                    ISK = data.Rates.ISK,
                    JEP = data.Rates.JEP,
                    JMD = data.Rates.JMD,
                    JOD = data.Rates.JOD,
                    JPY = data.Rates.JPY,
                    KES = data.Rates.KES,
                    KGS = data.Rates.KGS,
                    KHR = data.Rates.KHR,
                    KMF = data.Rates.KMF,
                    KPW = data.Rates.KPW,
                    KRW = data.Rates.KRW,
                    KWD = data.Rates.KWD,
                    KYD = data.Rates.KYD,
                    KZT = data.Rates.KZT,
                    LAK = data.Rates.LAK,
                    LBP = data.Rates.LBP,
                    LKR = data.Rates.LKR,
                    LRD = data.Rates.LRD,
                    LSL = data.Rates.LSL,
                    LTL = data.Rates.LTL,
                    LVL = data.Rates.LVL,
                    LYD = data.Rates.LYD,
                    MAD = data.Rates.MAD,
                    MDL = data.Rates.MDL,
                    MGA = data.Rates.MGA,
                    MKD = data.Rates.MKD,
                    MMK = data.Rates.MMK,
                    MNT = data.Rates.MNT,
                    MOP = data.Rates.MOP,
                    MRO = data.Rates.MRO,
                    MUR = data.Rates.MUR,
                    MVR = data.Rates.MVR,
                    MWK = data.Rates.MWK,
                    MXN = data.Rates.MXN,
                    MYR = data.Rates.MYR,
                    MZN = data.Rates.MZN,
                    NAD = data.Rates.NAD,
                    NGN = data.Rates.NGN,
                    NIO = data.Rates.NIO,
                    NOK = data.Rates.NOK,
                    NPR = data.Rates.NPR,
                    NZD = data.Rates.NZD,
                    OMR = data.Rates.OMR,
                    PAB = data.Rates.PAB,
                    PEN = data.Rates.PEN,
                    PGK = data.Rates.PGK,
                    PHP = data.Rates.PHP,
                    PKR = data.Rates.PKR,
                    PLN = data.Rates.PLN,
                    PYG = data.Rates.PYG,
                    QAR = data.Rates.QAR,
                    RON = data.Rates.RON,
                    RSD = data.Rates.RSD,
                    RUB = data.Rates.RUB,
                    RWF = data.Rates.RWF,
                    SAR = data.Rates.SAR,
                    SBD = data.Rates.SBD,
                    SCR = data.Rates.SCR,
                    SDG = data.Rates.SDG,
                    SEK = data.Rates.SEK,
                    SGD = data.Rates.SGD,
                    SHP = data.Rates.SHP,
                    SLL = data.Rates.SLL,
                    SOS = data.Rates.SOS,
                    SRD = data.Rates.SRD,
                    STD = data.Rates.STD,
                    SVC = data.Rates.SVC,
                    SYP = data.Rates.SYP,
                    SZL = data.Rates.SZL,
                    THB = data.Rates.THB,
                    TJS = data.Rates.TJS,
                    TMT = data.Rates.TMT,
                    TND = data.Rates.TND,
                    TOP = data.Rates.TOP,
                    TRY = data.Rates.TRY,
                    TTD = data.Rates.TTD,
                    TWD = data.Rates.TWD,
                    TZS = data.Rates.TZS,
                    UAH = data.Rates.UAH,
                    UGX = data.Rates.UGX,
                    USD = data.Rates.USD,
                    UYU = data.Rates.UYU,
                    UZS = data.Rates.UZS,
                    VEF = data.Rates.VEF,
                    VND = data.Rates.VND,
                    VUV = data.Rates.VUV,
                    WST = data.Rates.WST,
                    XAF = data.Rates.XAF,
                    XAG = data.Rates.XAG,
                    XAU = data.Rates.XAU,
                    XCD = data.Rates.XCD,
                    XDR = data.Rates.XDR,
                    XOF = data.Rates.XOF,
                    XPF = data.Rates.XPF,
                    YER = data.Rates.YER,
                    ZAR = data.Rates.ZAR,
                    ZMK = data.Rates.ZMK,
                    ZMW = data.Rates.ZMW,
                    ZWL = data.Rates.ZWL
                };
                context.Currencies.Add(currency);
                context.Rates.Add(rates);
                context.SaveChanges();
            }
        }
    }
}
